version: 2
jobs:
  build:
    working_directory: ~/Flow
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#         command: sudo chmod +x ./gradlew
      - run:
          name: Run Tests
          command: ./gradlew test
      - store_artifacts:
          path: flow/build/reports
          destination: reports
      - store_test_results:
          path: flow/build/test-results